apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: system
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30007
      port: 80
      protocol: TCP
      targetPort: 8087